import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import ThemeProvider from "@/components/Theme/ThemeProvider";
import "./globals.css";
import { Box } from "@mui/material";
import QueryProvider from "@/components/QueryProvider";
import { FavoriteProvider } from "@/context/FavoriteContext";
import { CartStoreProvider } from "@/store/cartProvider";

const vazir = Vazirmatn({
  variable: "--font-vazir-sans",
  subsets: ["latin", "arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa">
      <ThemeProvider>
        <FavoriteProvider>
          <CartStoreProvider>
            <Box
              bgcolor="background.paper"
              className={`${vazir.variable}`}
              component="body"
            >
              <QueryProvider>{children}</QueryProvider>
            </Box>
          </CartStoreProvider>
        </FavoriteProvider>
      </ThemeProvider>
    </html>
  );
}
